---
title: "Caterpillar Plot"
author: "Longfei Zhang"
date: "4/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
if (!require("glmtoolbox")) install.packages("glmtoolbox")
library(glmtoolbox)
pacman::p_load(knitr, gmodels, car, lmtest, VGAM, dplyr, ggpubr)
library(readr)
```


```{r}
load(file='./data_black.RData')
load(file='./data_nonblack.RData')
```


```{r}
mod_blc<-vglm(as.factor(event) ~ 0+factor(center)
                 +DON_HIST_DIAB
                 +DON_GENDER
                 +DON_BMI_C
                 +DON_AGE_C4
                 +DON_RACE
                 +DON_HTN
                 +REC_GENDER
                 +REC_BMI_C
                 +REC_COLD_ISCH_TM_20
                 +REC_AGE_C4
                 +REC_DIAB
                 +REC_DIAL_YRS,
                 data=data_black, family = multinomial(refLevel = 1))

gamma_death_blc <- coef(mod_blc)[2*(1:19)-1]
which(gamma_death_blc==median(gamma_death_blc))
vgamma_death_blc <- diag(vcovvlm(mod_blc))[2*(1:19)-1]

gamma_fail_blc <- coef(mod_blc)[2*(1:19)]
which(gamma_fail_blc==median(gamma_fail_blc))
vgamma_fail_blc <- diag(vcovvlm(mod_blc))[2*(1:19)]
```

```{r}
mod_nonblc<-vglm(as.factor(event) ~ 0+factor(center)
                 +DON_HIST_DIAB
                 +DON_GENDER
                 +DON_BMI_C
                 +DON_AGE_C4
                 +DON_RACE
                 +DON_HTN
                 +REC_GENDER
                 +REC_BMI_C
                 +REC_COLD_ISCH_TM_20
                 +REC_AGE_C4
                 +REC_DIAB
                 +REC_DIAL_YRS,
                 data=data_nonblack, family = multinomial(refLevel = 1))
gamma_death_nonblc <- coef(mod_nonblc)[2*(1:19)-1]
which(gamma_death_nonblc==median(gamma_death_nonblc))
vgamma_death_nonblc <- diag(vcovvlm(mod_nonblc))[2*(1:19)-1]

gamma_fail_nonblc <- coef(mod_nonblc)[2*(1:19)]
which(gamma_fail_nonblc==median(gamma_fail_nonblc))
vgamma_fail_nonblc <- diag(vcovvlm(mod_nonblc))[2*(1:19)]
```



```{r Standard Death Ratio (Black)}
dat_death_blc <- data_black %>% filter(event!=3) %>% mutate(center=17)
pred_tmp <- predictvglm(object = mod_blc, newdata = dat_death_blc, type = 'link', se.fit = T) 
pred_death_blc <- data.frame(eta = pred_tmp$fitted.values[,'log(mu[,2]/mu[,1])'])
pred_death_blc <- pred_death_blc %>%
          mutate(pi = logitlink(eta, inverse = T)) %>%
          mutate(center = data_black$center[data_black$event!=3]) %>%
          mutate(event = data_black$event[data_black$event!=3]) %>%
          group_by(center) %>%
          mutate(pred = sum(pi)) %>%
          mutate(obs = sum(event==2)) %>%
          mutate(n = n())%>%
          mutate(gprime2 = sum(exp(2*eta)/(1+exp(eta))^4)) %>%
          select(center, obs, pred, n, gprime2) %>%
          unique() %>%
          ungroup(center) %>%
          mutate(se = sqrt(gprime2*vgamma_death_blc)/pred) %>%
          mutate(se = se*as.integer(se<10)) %>%
          mutate(sdr = obs/pred) %>%
          mutate(uci = sdr + 1.96*se) %>%
          mutate(lci = sdr - 1.96*se) 

pred_death_blc$lci[pred_death_blc$lci<0] <- 0
pred_death_blc$uci[pred_death_blc$uci>100] <- 0
pred_death_blc
```          


```{r plot sdr(Black)}
plot_death_blc <- pred_death_blc %>% 
  mutate(center = paste("center",1:19)) %>%
  arrange(sdr) %>%
  mutate(center=factor(center, levels=center)) %>%
  ggplot(aes(y=center, x=sdr, xmin=lci, xmax=uci)) +
  geom_vline(xintercept=1, linetype="dashed", size=0.5) +
  geom_errorbarh(height=0.15, size=.5) + 
  geom_point(size=1.5) +
  scale_x_continuous(limits=c(0, 10)) +
  annotate("text", x=4, y="center 19", label="Reference=1", size=5) +
  labs(x="Standard Death Ratio (Black)", y="Center")
plot_death_blc
```


```{r Standard Graft Failure Ratio (Black)}
dat_fail_blc <- data_black %>% filter(event!=2) %>% mutate(center=19)
pred_tmp <- predictvglm(object = mod_blc, newdata = dat_fail_blc, type = 'link', se.fit = T) 
pred_fail_blc <- data.frame(eta = pred_tmp$fitted.values[,'log(mu[,3]/mu[,1])'])
pred_fail_blc <- pred_fail_blc %>%
          mutate(pi = logitlink(eta, inverse = T)) %>%
          mutate(center = data_black$center[data_black$event!=2]) %>%
          mutate(event = data_black$event[data_black$event!=2]) %>%
          group_by(center) %>%
          mutate(pred = sum(pi)) %>%
          mutate(obs = sum(event==3)) %>%
          mutate(n = n())%>%
          mutate(gprime2 = sum(exp(2*eta)/(1+exp(eta))^4)) %>%
          select(center, obs, pred, n, gprime2) %>%
          unique() %>%
          ungroup(center) %>%
          mutate(se = sqrt(gprime2*vgamma_fail_blc)/pred) %>%
          mutate(sfr = obs/pred) %>%
          mutate(uci = sfr + 1.96*se) %>%
          mutate(lci = sfr - 1.96*se) 

pred_fail_blc$lci[pred_fail_blc$lci<0] <- 0
pred_fail_blc
```


```{r plot sfr Black}
plot_fail_blc <- pred_fail_blc %>% 
  mutate(center = paste("center",1:19)) %>%
  arrange(sfr) %>%
  mutate(center=factor(center, levels=center)) %>%
  ggplot(aes(y=center, x=sfr, xmin=lci, xmax=uci)) +
  geom_vline(xintercept=1, linetype="dashed", size=0.5) +
  geom_errorbarh(height=0.15, size=.5) + 
  geom_point(size=1.5) +
  scale_x_continuous(limits=c(0, 3)) +
  annotate("text", x=2, y="center 17", label="Reference=1", size=5) +
  labs(x="Standard Graft Failure Ratio (Black)", y="Center")
plot_fail_blc
```



```{r Standard Death Ratio (nonBlack)}
dat_death_nonblc <- data_nonblack %>% filter(event!=3) %>% mutate(center=12)
pred_tmp <- predictvglm(object = mod_nonblc, newdata = dat_death_nonblc, type = 'link', se.fit = T) 
pred_death_nonblc <- data.frame(eta = pred_tmp$fitted.values[,'log(mu[,2]/mu[,1])'])
pred_death_nonblc <- pred_death_nonblc %>%
          mutate(pi = logitlink(eta, inverse = T)) %>%
          mutate(center = data_nonblack$center[data_nonblack$event!=3]) %>%
          mutate(event = data_nonblack$event[data_nonblack$event!=3]) %>%
          group_by(center) %>%
          mutate(pred = sum(pi)) %>%
          mutate(obs = sum(event==2)) %>%
          mutate(n = n())%>%
          mutate(gprime2 = sum(exp(2*eta)/(1+exp(eta))^4)) %>%
          select(center, obs, pred, n, gprime2) %>%
          unique() %>%
          ungroup(center) %>%
          mutate(se = sqrt(gprime2*vgamma_death_nonblc)/pred) %>%
          mutate(sdr = obs/pred) %>%
          mutate(uci = sdr + 1.96*se) %>%
          mutate(lci = sdr - 1.96*se) 

pred_death_nonblc$lci[pred_death_nonblc$lci<0] <- 0
pred_death_nonblc
```


```{r plot sdr nonblack}
plot_death_nonblc <- pred_death_nonblc %>% 
  mutate(center = paste("center",1:19)) %>%
  arrange(sdr) %>%
  mutate(center=factor(center, levels=center)) %>%
  ggplot(aes(y=center, x=sdr, xmin=lci, xmax=uci)) +
  geom_vline(xintercept=1, linetype="dashed", size=0.5) +
  geom_errorbarh(height=0.15, size=.5) + 
  geom_point(size=1.5) +
  scale_x_continuous(limits=c(0, 2.5)) +
  annotate("text", x=2, y="center 11", label="Reference=1", size=5) +
  labs(x="Standard Death Ratio (nonBlack)", y="Center")
plot_death_nonblc
```





```{r Standard Graft Failure Ratio (nonBlack)}
dat_fail_nonblc <- data_nonblack %>% filter(event!=2) %>% mutate(center=5)
pred_tmp <- predictvglm(object = mod_nonblc, newdata = dat_fail_nonblc, type = 'link', se.fit = T) 
pred_fail_nonblc <- data.frame(eta = pred_tmp$fitted.values[,'log(mu[,3]/mu[,1])'])
pred_fail_nonblc <- pred_fail_nonblc %>%
          mutate(pi = logitlink(eta, inverse = T)) %>%
          mutate(center = data_nonblack$center[data_nonblack$event!=2]) %>%
          mutate(event = data_nonblack$event[data_nonblack$event!=2]) %>%
          group_by(center) %>%
          mutate(pred = sum(pi)) %>%
          mutate(obs = sum(event==3)) %>%
          mutate(n = n())%>%
          mutate(gprime2 = sum(exp(2*eta)/(1+exp(eta))^4)) %>%
          select(center, obs, pred, n, gprime2) %>%
          unique() %>%
          ungroup(center) %>%
          mutate(se = sqrt(gprime2*vgamma_fail_nonblc)/pred) %>%
          mutate(sfr = obs/pred) %>%
          mutate(uci = sfr + 1.96*se) %>%
          mutate(lci = sfr - 1.96*se)

pred_fail_nonblc$lci[pred_fail_nonblc$lci<0] <- 0
pred_fail_nonblc
```
 
 
```{r plot sfr nonblack}
plot_fail_nonblc <- pred_fail_nonblc %>% 
  mutate(center = paste("center",1:19)) %>%
  arrange(sfr) %>%
  mutate(center=factor(center, levels=center)) %>%
  ggplot(aes(y=center, x=sfr, xmin=lci, xmax=uci)) +
  geom_vline(xintercept=1, linetype="dashed", size=0.5) +
  geom_errorbarh(height=0.15, size=.5) + 
  geom_point(size=1.5) +
  scale_x_continuous(limits=c(0, 3.2)) +
  annotate("text", x=2, y="center 11", label="Reference=1", size=5) +
  labs(x="Standard Graft Failure Ratio (nonBlack)", y="Center")
plot_fail_nonblc
```


```{r race disparity death}
sdr_diff <- data.frame(center = pred_death_blc$center, 
                         dsdr = pred_death_blc$sdr- pred_death_nonblc$sdr,
                         se = sqrt(pred_death_blc$se^2 + pred_death_nonblc$se^2))
sdr_diff$lci <- sdr_diff$dsdr - 1.96*sdr_diff$se
sdr_diff$uci <- sdr_diff$dsdr + 1.96*sdr_diff$se

plot_dsdr <- sdr_diff %>% 
  mutate(center = paste("center",1:19)) %>%
  arrange(dsdr) %>%
  mutate(center=factor(center, levels=center)) %>%
  ggplot(aes(y=center, x=dsdr, xmin=lci, xmax=uci)) +
  geom_vline(xintercept=0, linetype="dashed", size=0.5) +
  geom_errorbarh(height=0.15, size=.5) + 
  geom_point(size=1.5) +
  scale_x_continuous(limits=c(-3, 8)) +
  annotate("text", x=3, y="center 3", label="Reference=0", size=5) +
  labs(x="Difference of Standard Death Ratio", y="Center")
plot_dsdr
```

```{r race disparity of graft failure}
sfr_diff <- data.frame(center = pred_fail_blc$center, 
                         dsfr = pred_fail_blc$sfr- pred_fail_nonblc$sfr,
                         se = sqrt(pred_fail_blc$se^2 + pred_fail_nonblc$se^2))
sfr_diff$lci <- sfr_diff$dsfr - 1.96*sfr_diff$se
sfr_diff$uci <- sfr_diff$dsfr + 1.96*sfr_diff$se

plot_dsfr <- sfr_diff %>% 
  mutate(center = paste("center",1:19)) %>%
  arrange(dsfr) %>%
  mutate(center=factor(center, levels=center)) %>%
  ggplot(aes(y=center, x=dsfr, xmin=lci, xmax=uci)) +
  geom_vline(xintercept=0, linetype="dashed", size=0.5) +
  geom_errorbarh(height=0.15, size=.5) + 
  geom_point(size=1.5) +
  scale_x_continuous(limits=c(-2.5, 2.5)) +
  annotate("text", x=1.5, y="center 4", label="Reference=0", size=5) +
  labs(x="Difference of Standard Graft Failure Ratio", y="Center")
plot_dsfr
```







